### ISSUE TITLE
FEAT closes after converting a texture, which is problematic when batch converting files

### ISSUE THREAD

**Issue by robotortoise** [SciresM/FEAT#2]
FEAT closes after it starts converting a texture, which is problematic when batch converting files. Could you please post a release that either fixes this when batch converting, or removes the function to convert a texture to a picture automatically?

I can always do that manually.

**Comment by SciresM** [comment]
It is not supposed to close. Could you link me to the texture that's causing this? I can't reproduce it.

**Comment by robotortoise** [comment]
Any lz compressed file.

Like, anything in ui. For instance, system.ctpk.

I'm on Windows 10 64 bit.

**Comment by robotortoise** [comment]
Nevermind! I fixed it by simply recompiling it myself using Visual Studio 2015.

Thanks!

**Comment by robotortoise** [comment]
No, wait, I take it back. It still crashes when doing LZ-compressed .ctpk files.

Here's an example.

https://mega.nz/#!osZVSQ4Q!ym-9C0Dn8VM7LK0vZcmNFah1s7V1GlUp1AI-ML4xC5M
