### ISSUE TITLE
FEAT crashes when decompressing LZ files that contain ctpk files.

### ISSUE THREAD

**Issue by robotortoise** [SciresM/FEAT#3]
Sorry for opening a new issue, but I have more information this time around, so I figure this is the best way to do it.

I ran a debugger and this is the error that was shown. I can't code, so I don't know what it means....
I'm running Windows 10 Home x64. I'm using an Nvidia GPU and an AMD CPU.

Let me know what I can do to help.

-Robotortoise

![debug](https://cloud.githubusercontent.com/assets/7727806/12125766/6975401e-b3aa-11e5-853a-3437695698cb.png)

**Comment by 00Technocolor00** [comment]
yeah same here

**Comment by robotortoise** [comment]
Oh yeah, SciresM doesn't update this tool anymore. Go to https://github.com/DeathChaos25/FEAT for the updated Repo.
