### ISSUE TITLE
Encryption .bfnt does not work, only decryption

### ISSUE THREAD

**Issue by ghost** [SciresM/FEAT#8]
Encryption .bfnt does not work, only decryption. Why?

**Comment by SciresM** [comment]
Not really sure how to represent decrypted .bfnts in a re-packable way. FEAT only extracts the textures right now, anyway, doesn't even dump the character location data to a meaningful format.

**Comment by mihaltsov** [comment]
Bad news

**Comment by mihaltsov** [comment]
Maybe this will somehow help:
https://developer.nintendo.com/html/online-docs/3ds-en/ctr-en/ctrmc/Packages/SDK/CTRSDK/CTR_SDK_11_x/SDK/documents/api/nn/font/ResFont/Overview.html

**Comment by brothprd** [comment]
And will there be such an opportunity in the future?
I noticed that you got the files from the FE: Shadows of Valentia, so the translation is coming?
